name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/set-up-java@2 
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Create GCP Credentials
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > credentials.json 
        shell: bash 

      - name: Build with Maven 
        run: mvn -B package 
        env: 
          GCP_CREDENTIALS_LOCATION: file:$(pwd)/credentials.json
          GCP_PROJECT_ID: adv-swe-some

